---
title: "Books"
---

<hr>

<div class = "row">

<div class = "col-md-6">
The book "Manual de R" is available [in this url](https://fhernanb.github.io/Manual-de-R/).

```{r fig.asp=0.6, echo=FALSE}
library(png)
library(grid)
img <- readPNG("imagenes/cover_manualR.png")
grid.raster(img)
```
</div>

<div class = "col-md-6">
"Gráficos con R" is available [in this url](https://fhernanb.github.io/Graficos-con-R/).

```{r fig.asp=0.6, echo=FALSE}
library(png)
library(grid)
img <- readPNG("imagenes/cover_graficosR.png")
grid.raster(img)
```
</div>

</div>



<hr>



<div class = "row">

<div class = "col-md-6">
"Análisis de regresión con R" is available [in this url](https://fhernanb.github.io/libro_regresion/).

```{r fig.asp=0.6, echo=FALSE}
library(png)
library(grid)
img <- readPNG("imagenes/cover_regresionR.png")
grid.raster(img)
```
</div>


<div class = "col-md-6">
"Modelos Predictivos" is available [in this url](https://fhernanb.github.io/libro_mod_pred/).

```{r fig.asp=0.6, echo=FALSE}
library(png)
library(grid)
img <- readPNG("imagenes/cover_mod_pred.png")
grid.raster(img)
```
</div>


</div>

<hr>



<div class = "row">

<div class = "col-md-6">
"Modelos Mixtos con R" is available [in this url](https://fhernanb.github.io/libro_modelos_mixtos/).

```{r fig.asp=0.6, echo=FALSE}
library(png)
library(grid)
img <- readPNG("imagenes/cover_mod_mix.png")
grid.raster(img)
```
</div>

<iframe src="https://docs.google.com/document/d/e/2PACX-1vQ9w-jKaCqJsu7DoW60RY-tc7Ui-CtifUGKxn6AL03oGnL-XhxD2y9zbaMCNLRMAZVNPZC2oJK3pKZG/pub?embedded=true" style="width: 100%; height: 600px;"></iframe>

</div>