---
title: "Teaching"
---
Below are the courses and all of them have support with Moodle platform. You can access as guest using [this url](http://virtualciencias.medellin.unal.edu.co/moodle/course/index.php?categoryid=8) with the password: <font color="#9938E9">antioquia</font>

- 2020-20
    - Modelos jerárquicos
    - Seminario II de maestría
    - Análisis de regresióna
- 2020-10
    - Modelos Lineales Generalizados
- 2019-20
    - Modelos jerárquicos
    - Seminario II de maestría
    - Técnicas computacionales en estadística
- 2019-10
    - Simulación estadística
    - Análisis de regresión
- 2018-20
    - Introducción al análisis multivariado
    - Seminario II de maestría
    - Técnicas computacionales en estadística
- 2018-10
    - Elementos de probabilidad y estadística
    - Análisis de regresión
- 2017-20
    - Simulación estadística
    - Análisis de regresión
    - Seminario II de maestría
- 2017-10
    - Elementos de probabilidad y estadística
    - Regresión y diseño de experimentos
- 2016-20
    - Análisis de regresión
    - Introducción al análisis multivariado
    - Seminario de especialización
- 2016-01
    - Simulación estadística
    - Elementos de probabilidad y estadística.
- 2015-02
    - Modelos jerárquicos
    - Análisis de regresión
- 2015-01
    - Simulación estadística
    - Elementos de probabilidad y estadística

